version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql-jenkins-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsjenkinsdb
    volumes:
      - db_data:/var/lib/mysql

  backend:
    container_name: node-jenkins-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    container_name: react-jenkins-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  db_data:
